### ISSUE TITLE
Поправить прием данных

### ISSUE THREAD

**Issue by Olegdzhan** [Olegdzhan/travalon#10]
Сделай, чтобы все принималось как надо.

**Comment by dissdoc** [comment]
А как надо?

**Comment by Olegdzhan** [comment]
Чтобы я отправил тебе объект, переведенный в json, и он принялся. А сейчас у тебя ничего не принимается. Даже через Insomnia.
У тебя сейчас принимает только через адресную строку вида */?j_username=addfa&j_password=12235*
