### ISSUE TITLE
GET-данные при авторизации 200

### ISSUE THREAD

**Issue by Olegdzhan** [Olegdzhan/travalon#12]
При успешной авторизации от меня последует GET-запрос на весь объект *user*, включая новые поля. Обеспечь передачу.
```javascript
{
  "id"
  "email"
  "avatarURL"
  "firstName"
  "lastName"
}
```

**Comment by dissdoc** [comment]
Тогда я делаю просто GET /user и по сессии тебе передам данные. Вот только вопрос. Зачем тебе email на клиенте?

**Comment by Olegdzhan** [comment]
Согласен, email не нужен.
Но мне сразу нужно id сессии и id пользователя.

**Comment by dissdoc** [comment]
id сессии тебе зачем? :smile:

**Comment by Olegdzhan** [comment]
Не знаю, в примере про аутентификацию было.

Логика следующая:
1. Пользователь авторизуется, ему приходит его **id** и сохраняется в глобальной области видимости.
2. Сразу же происходит **$location.path('/app')**, т.е. переход в приложение.
3. Поступает GET на данные пользователя по id

**Comment by dissdoc** [comment]
Тебе сессию не нужно получать как таковую. Потому что она и так в браузере есть

**Comment by Olegdzhan** [comment]
Убери возврат lastname и firstname во время авторизации по ним будет запрос после срабатывания роута **/app**
Закрывай задачу, как уберешь.
