### ISSUE TITLE
Проверь структуру данных для пользователя

### ISSUE THREAD

**Issue by dissdoc** [Olegdzhan/travalon#5]
```json
{
    "id": "...",
    "firstName": "...",
    "lastName": "...",
    "password": "...",
    "email": "...",
    "avatar": "...."
}
```
Все верно? Если да, то закрывай задачу

**Comment by Olegdzhan** [comment]
предусмотри еще два свойства: 
**"campaign"** - булевое значение, размещает ли пользователь свои рекламные объявления; 
**"сampaignDueTo"** - дата окончания оплачиваемого периода по кампаниям

**Comment by dissdoc** [comment]
Уберу возраст пользователя. Вообще это ни к чему

**Comment by Olegdzhan** [comment]
Согласен.
В принципе, до регистрации объявлений еще далеко, так что пока можно и без этого поля.
