### ISSUE TITLE
Сделать отправку данных из формы авторизации

### ISSUE THREAD

**Issue by Olegdzhan** [Olegdzhan/travalon#6]
1. Директива авторизации
2. Контроллер авторизации + фабрика регистрации
3. Дополнить разметку чекбоксом "Запомнить"

адрес **/j_spring_security_check**
```javascript
{
    "j_username": "",
    "j_passowrd": "",
    "j_spring_security_remeber_me": "true/false"
}
```

**Comment by Olegdzhan** [comment]
я через консоль посмотрел, если до чекбокса не дотрагиваться, то уходит
```javascript
"j_spring_security_remember_me": "undefined"
```
надо дописывать что если **undefined**, то равно **false**, или там само все у тебя разберется?

Если не надо, то закрываю задачу.

**Comment by dissdoc** [comment]
Нет, тут два варианта получается
1. Либо ты делаешь у себя дефолтный false
2. Либо ты этот параметр не отправляешь, если он не выбран

Первый вариант предпочтительней. Undefined - это уже значение, и она не кастится на boolean тип, в результате сервер отдавать будет Cast Exception (типа такого)

**Comment by Olegdzhan** [comment]
```javascript
authFC.user.rememberMe = authFC.user.rememberMe || false;
```
Готово
