### ISSUE TITLE
Валидация на сервере и возврат данных

### ISSUE THREAD

**Issue by Olegdzhan** [Olegdzhan/travalon#7]
##### Валидация email'a
Необходимо проверить на уникальность и на возможность отправки почты.
Вернуть ошибки или подтверждение email'a. 

Реши как сделать подтверждение: через ссылку или через код подтверждения.
На мой взгляд, через код удобнее: все равно у всех почтовые клиенты на смартфонах, так что получается аналогия с смс-конфёрмом.

###### P.S.
валидация паролей на сложность и совпадение с повтором, проходит на клиенте.

**Comment by dissdoc** [comment]
Задачи:
1. Проверка на повторяемость email'ов
2. Отправка сообщения на почту
3. Формирование кода подтверждения

Будут делаться во второй итерации, в данный момент это не имеет смысла. В первой итерации должно все работать, описывая бизнес-процессы
