### ISSUE TITLE
Данные авторизации

### ISSUE THREAD

**Issue by Olegdzhan** [Olegdzhan/travalon#9]
###### Авторизация
какие данные я получу по успеху/неуспеху?

###### Регистрация
после успешной регистрации, я должен авторизоваться, так что опять же должен получить эти данные.
какие ошибки я получу после непрошедшей регистрации?

**Comment by dissdoc** [comment]
Смотри, после успешной авторизации, ты получаешь ответ 200 OK 
После логина ты получаешь 200 OK и json вида 
{
    id: '12',
    firstName: '',
    lastName: ''
}


В случае неуспеха при регистрации или авторизации - ты получаешь 401 Unauthorize
